# Generated by Django 5.0.13 on 2025-11-29 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_viajes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alojamiento',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='alojamiento',
            name='pais',
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_viajes.destino'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_destino', to='app_viajes.destino'),
        ),
        migrations.AlterField(
            model_name='vuelo',
            name='origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_origen', to='app_viajes.destino'),
        ),
    ]
