# Generated by Django 5.0.13 on 2025-12-02 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_viajes', '0002_remove_alojamiento_ciudad_remove_alojamiento_pais_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete_turistico',
            name='incluye_alojamiento',
        ),
        migrations.RemoveField(
            model_name='paquete_turistico',
            name='incluye_vuelo',
        ),
        migrations.RemoveField(
            model_name='reserva_viaje',
            name='id_paquete',
        ),
        migrations.AddField(
            model_name='reserva_viaje',
            name='id_alojamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_viajes.alojamiento'),
        ),
        migrations.AddField(
            model_name='reserva_viaje',
            name='id_vuelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_viajes.vuelo'),
        ),
    ]
