# Generated by Django 5.0.13 on 2025-12-02 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_viajes', '0003_remove_paquete_turistico_incluye_alojamiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete_turistico',
            name='alojamientos',
            field=models.ManyToManyField(blank=True, related_name='paquetes', to='app_viajes.alojamiento'),
        ),
        migrations.AddField(
            model_name='paquete_turistico',
            name='vuelos',
            field=models.ManyToManyField(blank=True, related_name='paquetes', to='app_viajes.vuelo'),
        ),
        migrations.AddField(
            model_name='reserva_viaje',
            name='id_paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_viajes.paquete_turistico'),
        ),
    ]
